### PR TITLE
Add `withIcon` to button

### PR DESCRIPTION
**Pull request by tennety**
Apologies for making an unsolicited pull request!

I was looking to implement Brian's Robot Buttons idea and ran into this repo. The one thing I was looking for that was missing was the ability to add an icon to the button. So I decided to fork and play around to see if I could make it work. This PR is the result. Happy to incorporate any feedback, or close if you are not accepting pulls at this time. Thanks again for all you do in the Elm community!

### CODE REVIEW

**Comment by jxxcarlson** [comment]
Thank you very much!  I will look at this later today.  This is most welcome.

— Jim

**Comment by jxxcarlson** [comment]
Hey, sorry I didn't merge this earlier.  Nice work!

**Comment by tennety** [comment]
Wonderful, thank you Jim! ❤️

**Comment by jxxcarlson** [comment]
OK, the package is published with your merged pull request.  Great addition!

**Comment by jxxcarlson** [comment]
I will publish the updated version of the package today … forgot that step!

Wanted to get this out … as soon as I have time I will put a credit to your contribution in the README.

Best regards,

JIm

**Pull request merged**
